/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import configuracoes.EstiloFrame;
import constantes.Diretorio;
import cora.Sorteio;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus Simões
 */
public class SortearUI extends javax.swing.JFrame {
    /**
     * Creates new form SortearUI
     */
    private final String dirCompeticao = Diretorio.COMPETICAO.getValue();
    private int numeroTotalEquipes=0;
    private final List<String> listaSorteioBateria = new ArrayList();
    private final List<String> listaSorteioFinalistas = new ArrayList();
    public SortearUI() throws IOException {
        initComponents();
        
        btnSorteio.setEnabled(false);
       
        iniciarFrame();  
        inicializaListaPresenca();
        
    }
    
    private void iniciarFrame() {
        
        EstiloFrame estilo = new EstiloFrame();
        estilo.icone(this, "/imagens/dados.png");
        estilo.botao(btnresetaBateria, "/imagens/dados.png");
        estilo.botao(btnSorteio, "/imagens/raffle.png");
              
    }
    private void inicializaListaPresenca() throws FileNotFoundException, IOException{
        int rowCounter=0;
        int count = 0;
        int indiceEquipe = 0;
        String indice="";
            FileReader leituraEquipes = new FileReader(dirCompeticao.concat("/listaEquipes/equipes.txt"));
            BufferedReader buff = new BufferedReader(leituraEquipes);
                    // PEGA OS INDICES DAS EQUIPES SORTEADAS E COMPARA PRA VERIFICAR QUAIS SÃO AS EQUIPES                           
                        while(buff.ready() && rowCounter<=24){
                            String linha = buff.readLine(); 
                            String splitLinha[] = linha.split(":");
                            tabelaPresenca.setValueAt(splitLinha[1], rowCounter, 0);
                            indice = splitLinha[0];       
                            rowCounter++;
                            count++;
                        }       
                        // Evita NullException
                        for(int i = 0; i<=24;i++){
                            tabelaPresenca.setValueAt((boolean) false, i, 1);
                        }
                        if(count>9){
                        numeroTotalEquipes = Integer.parseInt(indice.substring(0,2));
                        } else {
                        numeroTotalEquipes = Integer.parseInt(indice.substring(0,1));
                        }
                        
    }
    
    private void sorteio(){
        for(int row=0; row<numeroTotalEquipes;row++){
            if((boolean) tabelaPresenca.getValueAt(row, 1)==true){
                listaSorteioBateria.add((String) tabelaPresenca.getValueAt(row, 0));
            }
        }
        Collections.shuffle(listaSorteioBateria); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radiobtnClassificatoria = new javax.swing.JRadioButton();
        radiobtnFinal = new javax.swing.JRadioButton();
        btnSorteio = new javax.swing.JButton();
        btnresetaBateria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEquipes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPresenca = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sorteio da Ordem das Equipes");
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sorteio das Baterias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selecione a Bateria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        buttonGroup1.add(radiobtnClassificatoria);
        radiobtnClassificatoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiobtnClassificatoria.setSelected(true);
        radiobtnClassificatoria.setText("Bateria Classificatória");
        radiobtnClassificatoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiobtnClassificatoriaStateChanged(evt);
            }
        });
        radiobtnClassificatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnClassificatoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnFinal);
        radiobtnFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiobtnFinal.setText("Bateria Final");
        radiobtnFinal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiobtnFinalStateChanged(evt);
            }
        });
        radiobtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiobtnFinal)
                    .addComponent(radiobtnClassificatoria))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtnClassificatoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtnFinal))
        );

        btnSorteio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSorteio.setText("SORTEAR");
        btnSorteio.setMaximumSize(new java.awt.Dimension(153, 23));
        btnSorteio.setMinimumSize(new java.awt.Dimension(153, 23));
        btnSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteioActionPerformed(evt);
            }
        });

        btnresetaBateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnresetaBateria.setText("INICIAR NOVO SORTEIO");
        btnresetaBateria.setActionCommand("INICIAR\nNOVO SORTEIO");
        btnresetaBateria.setPreferredSize(new java.awt.Dimension(201, 56));
        btnresetaBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetaBateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnresetaBateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnresetaBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("<html><b>Selecione a Bateria</b></html>");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CoRA.png"))); // NOI18N

        jScrollPane1.setBorder(null);

        tabelaEquipes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelaEquipes.setRowHeight(40);
        tabelaEquipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Ordem das Equipes na Bateria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        jScrollPane1.setViewportView(tabelaEquipes);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Presença", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        tabelaPresenca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelaPresenca.setRowHeight(40);
        tabelaPresenca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Equipe", "Presença"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaPresenca);
        if (tabelaPresenca.getColumnModel().getColumnCount() > 0) {
            tabelaPresenca.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 38, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetaBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetaBateriaActionPerformed
        // TODO add your handling code here:

        Sorteio sortear = new Sorteio();
        boolean continua = !(sortear.testaArquivo());
            if(continua){
                int selectedOption = JOptionPane.showConfirmDialog(null, 
                    "Deseja Realizar um Novo sorteio?", 
                    "Finalizar", 
                    JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) {
                    DefaultTableModel table = (DefaultTableModel) tabelaEquipes.getModel();
                    for(int i = 0; i<=29;i++){
                            tabelaEquipes.setValueAt("", i, 0);
                        }
                    listaSorteioBateria.clear();
                    listaSorteioFinalistas.clear();
                    btnSorteio.setEnabled(true);
                    JOptionPane.showMessageDialog(null,"Novo sorteio já pode ser realizado!");
            }
            }else{
            JOptionPane.showMessageDialog(rootPane, "Não existem equipes cadastradas!");
            }
    }//GEN-LAST:event_btnresetaBateriaActionPerformed

    private void radiobtnClassificatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnClassificatoriaActionPerformed
        // TODO add your handling code here:

        try {
            inicializaListaPresenca();
        } catch (IOException ex) {
            Logger.getLogger(SortearUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_radiobtnClassificatoriaActionPerformed

    private void btnSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteioActionPerformed
        // Sorteio classificatoria
        Sorteio sortear = new Sorteio();
        boolean clasFinal = radiobtnClassificatoria.isSelected();
            if (radiobtnClassificatoria.isSelected() == true) {
                String arq = sortear.arquivoBateria(clasFinal);
                sorteio();
                DefaultTableModel table = (DefaultTableModel) tabelaEquipes.getModel();
                JOptionPane.showMessageDialog(null,"Todas as equipes foram sorteadas!");
                for(int i = listaSorteioBateria.size(); i>=1;i--){
                    tabelaEquipes.setValueAt((i)+"º" + " - " + listaSorteioBateria.get(i-1), i-1, 0);
                }
                
            try {
                sortear.escreveTxtBateria(listaSorteioBateria,arq);
            } catch (IOException ex) {
                Logger.getLogger(SortearUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                btnSorteio.setEnabled(false);
        } else if (radiobtnFinal.isSelected() == true) {
            try {
                String arq = sortear.arquivoBateria(clasFinal);
                sorteio();    
                DefaultTableModel table2 = (DefaultTableModel) tabelaEquipes.getModel();
                         JOptionPane.showMessageDialog(null,"Todas as equipes foram sorteadas!");
                        for(int i = listaSorteioBateria.size(); i>=1;i--){
                            tabelaEquipes.setValueAt((i)+"º" + " - " + listaSorteioBateria.get(i-1), i-1, 0);
                        }
                sortear.escreveTxtBateria(listaSorteioBateria,arq);
                        btnSorteio.setEnabled(false);
            } catch (IOException ex) {
                Logger.getLogger(SortearUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSorteioActionPerformed

    private void radiobtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnFinalActionPerformed
        try {
            // TODO add your handling code here:
            for(int i = 0; i<=24; i++){
                tabelaPresenca.setValueAt("", i, 0);
            }
            preencheFinalistas();
        } catch (IOException ex) {
            Logger.getLogger(SortearUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_radiobtnFinalActionPerformed

    private void preencheFinalistas() throws FileNotFoundException, IOException{
            int row = 0;
            FileReader leituraEquipes = new FileReader(dirCompeticao.concat("/listaEquipes/equipes.txt"));
            BufferedReader buff = new BufferedReader(leituraEquipes);  
                    while(buff.ready()){
                       boolean okFinalista;
                       String linha = buff.readLine();     
                       String splitLinha[] = linha.split(":");                     
                       int simFinalista = Integer.parseInt(splitLinha[4].substring(1, 2));
                       if(simFinalista==1){
                           okFinalista = true;
                       } else {
                           okFinalista=false;
                       }
                       if(okFinalista){
                           tabelaPresenca.setValueAt(splitLinha[1],row,0);
                           row++;
                       }
                       for(int i = 0; i<=24;i++){
                            tabelaPresenca.setValueAt((boolean) false, i, 1);
                        }
                    }
    }
    private void radiobtnFinalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiobtnFinalStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radiobtnFinalStateChanged

    private void radiobtnClassificatoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiobtnClassificatoriaStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radiobtnClassificatoriaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortearUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortearUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortearUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortearUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new SortearUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SortearUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSorteio;
    private javax.swing.JButton btnresetaBateria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radiobtnClassificatoria;
    private javax.swing.JRadioButton radiobtnFinal;
    private javax.swing.JTable tabelaEquipes;
    private javax.swing.JTable tabelaPresenca;
    // End of variables declaration//GEN-END:variables
}
